"""
AI Content Generator Service
Handles all content generation using LangChain + OpenAI (or demo mode)
"""
import random
from typing import Optional, List
from app.models.schemas import ContentType, ToneType, ContentRequest, ContentResponse
from app.config import settings


# ═══════════════════════════════════════════════════════════
# PROMPT TEMPLATES for each content type
# ═══════════════════════════════════════════════════════════

PROMPT_TEMPLATES = {
    ContentType.BLOG: """Write a compelling blog post about: {topic}

Tone: {tone}
{keywords_section}
{audience_section}
{instructions_section}

Requirements:
- Include an attention-grabbing headline
- Write 3-5 well-structured paragraphs
- Use subheadings for readability
- Include a call-to-action at the end
- Make it SEO-friendly
{length_section}
""",

    ContentType.EMAIL: """Write a marketing email about: {topic}

Tone: {tone}
{keywords_section}
{audience_section}
{instructions_section}

Requirements:
- Compelling subject line
- Personalized greeting
- Clear value proposition in the first sentence
- Body with key benefits (use bullet points)
- Strong call-to-action button text
- Professional sign-off
{length_section}
""",

    ContentType.AD_COPY: """Write advertising copy for: {topic}

Tone: {tone}
Platform: {platform}
{keywords_section}
{audience_section}
{instructions_section}

Requirements:
- Hook/attention grabber (first line)
- Key benefit statement
- Social proof element
- Urgency/scarcity element
- Clear CTA
- Keep it concise and punchy
{length_section}
""",

    ContentType.CAPTION: """Write a social media caption for: {topic}

Tone: {tone}
Platform: {platform}
{keywords_section}
{audience_section}
{instructions_section}

Requirements:
- Engaging opening hook
- Storytelling or value-driven body
- Relevant emojis (tasteful, not excessive)
- Call-to-action
- 3-5 relevant hashtags at the end
{length_section}
""",

    ContentType.SEO_CONTENT: """Write SEO-optimized content about: {topic}

Tone: {tone}
{keywords_section}
{audience_section}
{instructions_section}

Requirements:
- SEO-optimized title with primary keyword
- Meta description (155 characters)
- Introduction with keyword in first paragraph
- H2 and H3 subheadings with keywords
- Natural keyword placement (2-3% density)
- Internal/external link suggestions
- Conclusion with CTA
{length_section}
""",

    ContentType.HEADLINE: """Generate 10 headline variations for: {topic}

Tone: {tone}
{keywords_section}
{audience_section}
{instructions_section}

Requirements:
- Mix of styles: question, how-to, listicle, emotional, data-driven
- Each headline should be under 70 characters
- Include power words
- A/B testing ready
""",

    ContentType.PRODUCT_DESCRIPTION: """Write a product description for: {topic}

Tone: {tone}
{keywords_section}
{audience_section}
{instructions_section}

Requirements:
- Benefit-focused headline
- Key features (bullet points)
- Emotional appeal paragraph
- Technical specifications section
- Social proof placeholder
- Clear CTA
{length_section}
""",
}


# ═══════════════════════════════════════════════════════════
# DEMO CONTENT (when running without OpenAI key)
# ═══════════════════════════════════════════════════════════

DEMO_CONTENT = {
    ContentType.BLOG: """# {topic}: A Complete Guide for Modern Businesses

## Why {topic} Matters in 2026

In today's rapidly evolving digital landscape, **{topic}** has become more critical than ever for businesses looking to stay competitive. Whether you're a startup or an established enterprise, understanding and leveraging this is non-negotiable.

## Key Strategies to Implement

### 1. Start with Your Audience
The most successful approaches begin with deep audience understanding. Use data-driven insights to map your customer journey and identify the touchpoints that matter most.

### 2. Leverage AI-Powered Tools
Modern AI tools can automate repetitive tasks, generate personalized content at scale, and provide predictive analytics that help you stay ahead of trends.

### 3. Measure What Matters
Don't get lost in vanity metrics. Focus on KPIs that directly impact your bottom line: conversion rates, customer lifetime value, and return on ad spend.

## The Bottom Line

{topic} isn't just a trend — it's the future of business growth. Companies that invest in this now will be the industry leaders of tomorrow.

**Ready to transform your approach to {topic}?** Start your free trial today and see the difference AI-powered marketing can make.

---
*This content was generated by MarkAI — your AI-powered marketing assistant.*""",

    ContentType.EMAIL: """**Subject Line:** 🚀 Unlock the Power of {topic} — Exclusive Offer Inside

---

Hi {{{{first_name}}}},

I know your inbox is crowded, so I'll keep this short and valuable.

**We've discovered something game-changing about {topic}** — and we want you to be the first to know.

Here's what you'll get:

• ✅ **Increased Engagement** — Up to 3x more interactions with your audience
• ✅ **Time Savings** — Automate 80% of your repetitive marketing tasks
• ✅ **Better ROI** — Our users see an average 40% improvement in campaign performance

**The best part?** You can get started in under 5 minutes.

[👉 Start Your Free Trial Now]

This exclusive offer expires in 48 hours, so don't miss out.

To your success,
The MarkAI Team

P.S. — Over 10,000 businesses already trust MarkAI for their {topic} needs. Join them today.""",

    ContentType.AD_COPY: """🔥 Stop wasting time on {topic} that doesn't convert.

Here's the truth: 90% of businesses are doing it wrong.

We built an AI that:
→ Generates high-converting content in seconds
→ Personalizes every campaign for YOUR audience
→ Optimizes performance automatically

Join 10,000+ businesses who've 3x'd their results.

🎯 Try it FREE for 14 days. No credit card required.

[Get Started Now →]""",

    ContentType.CAPTION: """✨ Ever wondered how top brands crush it with {topic}?

Here's what they know that you don't (yet) 👇

The secret isn't working harder — it's working smarter with AI.

Imagine having a team of expert marketers working 24/7, crafting perfect content, optimizing every campaign, and never taking a day off.

That's what MarkAI does for your business. 🚀

Ready to level up? Link in bio 🔗

#AIMarketing #{topic_tag} #ContentAutomation #DigitalMarketing #MarketingAI""",

    ContentType.SEO_CONTENT: """# The Ultimate Guide to {topic} in 2026

**Meta Description:** Discover proven strategies for {topic}. Learn how AI-powered tools can boost your results by 3x. Complete guide with actionable tips.

## What is {topic}?

{topic} is one of the most impactful strategies in modern digital marketing. According to recent studies, businesses that invest in this area see an average ROI of 300%.

## Why {topic} is Essential for Your Business

### H2: Increased Visibility and Traffic
When done right, {topic} can drive organic traffic growth of 50-100% within 6 months.

### H2: Better Customer Engagement
Personalized approaches to {topic} result in 2-3x higher engagement rates.

### H2: Competitive Advantage
Only 23% of businesses currently leverage AI for {topic} — early adopters gain significant market advantages.

## How to Get Started with {topic}

### Step 1: Audit Your Current Approach
### Step 2: Define Clear Goals and KPIs
### Step 3: Implement AI-Powered Tools
### Step 4: Monitor, Analyze, and Optimize

## Conclusion

{topic} is no longer optional — it's the cornerstone of modern marketing success. Start implementing these strategies today.

**[Start your free trial with MarkAI →]**""",

    ContentType.HEADLINE: """Here are 10 headline variations:

1. "How {topic} is Changing the Game for Small Businesses"
2. "7 Proven {topic} Strategies That Boost Revenue by 300%"
3. "Is Your Business Missing Out on {topic}? Here's How to Fix It"
4. "The Ultimate {topic} Playbook: From Zero to Hero"
5. "Why Smart Businesses are Investing in {topic} Right Now"
6. "{topic} Made Simple: A Step-by-Step Guide for Beginners"
7. "Breaking: New {topic} Trends That Will Dominate 2026"
8. "Stop Guessing: Use AI to Master {topic} Today"
9. "From $0 to $1M: How {topic} Transformed These Brands"
10. "The {topic} Secret No One is Talking About (Until Now)" """,

    ContentType.PRODUCT_DESCRIPTION: """## {topic} — The All-in-One Solution

**Transform your marketing with the power of AI.**

### Key Features:
• 🤖 **AI Content Generator** — Blog posts, emails, ads & captions in seconds
• 📊 **Smart Analytics** — Know exactly what's working and why
• 🚀 **Campaign Automation** — Set it and forget it across all platforms
• 🎯 **Personalization Engine** — Every message tailored to your audience
• 📈 **Performance Optimizer** — AI that improves your campaigns automatically

### Why Choose MarkAI?

Built by marketers, powered by AI. We understand the challenges small businesses face because we've been there. MarkAI isn't just another tool — it's your unfair advantage.

**⭐ Trusted by 10,000+ businesses | 4.9/5 rating | 99.9% uptime**

### Plans Starting at $29/month

🎁 **Try Free for 14 Days** — No credit card required.

[Start Your Free Trial →]""",
}


def _build_prompt(request: ContentRequest, brand_context: Optional[str] = None) -> str:
    """Build the full prompt from template and request parameters."""
    template = PROMPT_TEMPLATES.get(request.content_type, PROMPT_TEMPLATES[ContentType.BLOG])

    keywords_section = ""
    if request.keywords:
        keywords_section = f"Target Keywords: {', '.join(request.keywords)}"

    audience_section = ""
    if request.target_audience:
        audience_section = f"Target Audience: {request.target_audience}"

    instructions_section = ""
    if request.additional_instructions:
        instructions_section = f"Additional Instructions: {request.additional_instructions}"

    length_section = ""
    if request.max_length:
        length_section = f"Target Length: approximately {request.max_length} words"

    platform = request.platform or "general"

    prompt = template.format(
        topic=request.topic,
        tone=request.tone.value,
        keywords_section=keywords_section,
        audience_section=audience_section,
        instructions_section=instructions_section,
        length_section=length_section,
        platform=platform,
    )

    if brand_context:
        prompt = f"""Brand Context (use this to personalize the content):
{brand_context}

---

{prompt}"""

    return prompt


def _get_demo_content(request: ContentRequest) -> str:
    """Return demo content for the given content type."""
    template = DEMO_CONTENT.get(request.content_type, DEMO_CONTENT[ContentType.BLOG])
    topic_tag = request.topic.replace(" ", "").replace("-", "")[:20]
    return template.format(topic=request.topic, topic_tag=topic_tag)


def _calculate_seo_score(content: str, keywords: Optional[List[str]] = None) -> float:
    """Calculate a basic SEO score based on content analysis."""
    score = 50.0  # base score

    # Length bonus
    word_count = len(content.split())
    if word_count > 300:
        score += 10
    if word_count > 800:
        score += 10

    # Has headings
    if "#" in content:
        score += 10

    # Keyword usage
    if keywords:
        content_lower = content.lower()
        keyword_matches = sum(1 for kw in keywords if kw.lower() in content_lower)
        keyword_ratio = keyword_matches / len(keywords) if keywords else 0
        score += keyword_ratio * 20

    return min(score, 100.0)


async def generate_content(
    request: ContentRequest,
    brand_context: Optional[str] = None,
) -> ContentResponse:
    """
    Generate AI content based on the request.
    Uses OpenAI when available, otherwise returns demo content.
    """
    if settings.demo_mode or settings.openai_api_key == "demo":
        # Demo mode — return pre-built content
        content = _get_demo_content(request)
    else:
        # Production mode — use LangChain + OpenAI
        from langchain_openai import ChatOpenAI
        from langchain.schema import HumanMessage

        llm = ChatOpenAI(
            model=settings.openai_model,
            temperature=settings.temperature,
            max_tokens=settings.max_tokens,
            openai_api_key=settings.openai_api_key,
        )

        prompt = _build_prompt(request, brand_context)
        response = await llm.ainvoke([HumanMessage(content=prompt)])
        content = response.content

    # Calculate metadata
    word_count = len(content.split())
    keywords_used = []
    if request.keywords:
        content_lower = content.lower()
        keywords_used = [kw for kw in request.keywords if kw.lower() in content_lower]

    seo_score = _calculate_seo_score(content, request.keywords)

    suggestions = _generate_suggestions(request, seo_score)

    return ContentResponse(
        content=content,
        content_type=request.content_type,
        tone=request.tone,
        word_count=word_count,
        seo_score=seo_score,
        keywords_used=keywords_used,
        suggestions=suggestions,
    )


def _generate_suggestions(request: ContentRequest, seo_score: float) -> List[str]:
    """Generate improvement suggestions based on content analysis."""
    suggestions = []

    if seo_score < 70:
        suggestions.append("Consider adding more target keywords naturally throughout the content")

    if request.content_type == ContentType.BLOG and not request.keywords:
        suggestions.append("Add SEO keywords to improve search engine visibility")

    if request.content_type == ContentType.EMAIL:
        suggestions.append("A/B test different subject lines for higher open rates")
        suggestions.append("Add personalization tokens like {{first_name}} for better engagement")

    if request.content_type == ContentType.AD_COPY:
        suggestions.append("Test multiple CTA variations to optimize click-through rates")

    if request.content_type == ContentType.CAPTION:
        suggestions.append("Post during peak engagement hours (9 AM, 12 PM, or 7 PM)")

    # Always add a general tip
    general_tips = [
        "Use A/B testing to compare content variations",
        "Analyze engagement metrics to refine your content strategy",
        "Consider your audience's stage in the buyer journey",
        "Repurpose this content across multiple channels for maximum reach",
    ]
    suggestions.append(random.choice(general_tips))

    return suggestions
